apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo-stg
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '1.2.9' # {"$promotion": "default:app-podinfo-devteam1-host25-cluster30:stg"}
  targetNamespace: app-podinfo-stg
  values:
    service:
      enabled: false
      externalPort: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/service-upstream: "true"
        metadata.weave.works/app-url: http://demo3-cluster30.weavegitops.com/stg/podinfo/
      hosts:
        - host: demo3-cluster30.weavegitops.com
          paths:
            - path: "/stg/podinfo/?(.*)"
              pathType: Prefix
            - path: "/stg/(api/?.*)"
              pathType: Prefix
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for stg"
      color: ""
    canary:
      enabled: true
      loadtester:
        url: flagger-flagger-loadtester.flagger
      ingress:
        url: demo3-cluster30.weavegitops.com/stg/podinfo/
    hpa:
      enabled: true
      maxReplicas: 1
