apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '>=0.0.3'
  values:
    podinfo:
      replicas: 1
      ui:
        message: "Hi, this message is from the Helm values for dev-test"
        color: ""
