apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    templates.weave.works/template-name: app-podinfo-chart-and-pipeline-devteam1
    templates.weave.works/template-namespace: default
  name: promotion-credentials-app-podinfo-dev-sandbox
  namespace: devteam1
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weavegitops/application-promotion-podinfo\",\"head_branch\":\"wge-create-branch-l4xq99\",\"base_branch\":\"main\",\"title\":\"Create resource \",\"description\":\"This PR creates a app-podinfo-chart-and-pipeline-devteam1 instance\",\"template_name\":\"app-podinfo-chart-and-pipeline-devteam1\",\"parameter_values\":{\"CLUSTER_NAME\":\"dev-sandbox\",\"CLUSTER_NAMESPACE\":\"devteam1\",\"CLUSTER_URL\":\"dev-sandbox-devteam1.sa-demo.trial.cx.weave.works\",\"DEV_NAMESPACE\":\"app-podinfo-dev\",\"PRD_NAMESPACE\":\"app-podinfo-prd\",\"STG_NAMESPACE\":\"app-podinfo-stg\"},\"commit_message\":\"Create app-podinfo-chart-and-pipeline-devteam1 instance\",\"credentials\":{},\"template_namespace\":\"devteam1\",\"template_kind\":\"GitOpsTemplate\"}"
spec:
  dataFrom:
  - extract:
      key: demo/promotion/github/promotion-credentials
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretstore
  target:
    creationPolicy: Owner
    name: promotion-credentials-app-podinfo-dev-sandbox
