apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo-dev
  annotations:
    metadata.weave.works/app-url: http://sademo-devteam.weavegitops.com/dev/podinfo/
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: x.x.x # {"$promotion": "default:app-podinfo-devteam:dev"}
  targetNamespace: app-podinfo-dev
  test:
    enable: true
    timeout: 5m
    ignoreFailures: false
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  values:
    service:
      enabled: false
      externalPort: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/service-upstream: "true"
        external-dns.alpha.kubernetes.io/hostname: sademo-devteam.weavegitops.com
      hosts:
        - host: sademo-devteam.weavegitops.com
          paths:
            - path: "/dev/podinfo/?(.*)"
              pathType: Prefix
            - path: "/dev/(api/?.*)"
              pathType: Prefix
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for dev"
      color: ""
    canary:
      enabled: true
      loadtester:
        url: flagger-flagger-loadtester.flagger
      ingress:
        url: sademo-devteam.weavegitops.com/dev/podinfo/
    hpa:
      enabled: true
      maxReplicas: 1
