apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  annotations:
    metadata.weave.works/app-url: http://${cluster_url}/${environment:=dev}/podinfo/
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
  targetNamespace: app-podinfo-${environment:=dev}
  test:
    enable: true
    timeout: 5m
    ignoreFailures: false
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  values:
    service:
      enabled: false
      externalPort: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/service-upstream: "true"
      hosts:
        - host: ${cluster_url}
          paths:
            - path: "/${environment:=dev}/podinfo/?(.*)"
              pathType: Prefix
            - path: "/${environment:=dev}/(api/?.*)"
              pathType: Prefix
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for ${environment:=dev}"
      color: ""
    canary:
      enabled: true
      loadtester:
        url: flagger-flagger-loadtester.flagger
      ingress:
        url: ${cluster_url}/${environment:=dev}/podinfo/
    hpa:
      enabled: true
      maxReplicas: 1
