apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: podinfo-kustomize-sync
  namespace: flux-system
spec:
  providerRef:
    name: github-app-podinfo
  summary: "env=dev"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: app-promo-podinfo-dev-test
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: podinfo-dispatch
  namespace: flux-system
spec:
  providerRef:
    name: github-dispatch-app-podinfo
  summary: "env=dev"
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: podinfo
      namespace: app-podinfo
  exclusionList:
    - ".*upgrade.*has.*started"
    - ".*is.*not.*ready"
    - "^Dependencies.*"
