apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo-prd
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '1.2.2' # {"$promotion": "default:app-podinfo:prd"}
  targetNamespace: app-podinfo-prd
  values:
    service:
      enabled: false
      externalPort: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/service-upstream: "true"
      hosts:
        - host: demo3-cluster24.weavegitops.com
          paths:
            - path: "/prd/podinfo/?(.*)"
              pathType: Prefix
            - path: "/prd/(api/?.*)"
              pathType: Prefix
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for prd"
      color: ""
    canary:
      enabled: true
      loadtester:
        url: flagger-loadtester.flux-system
      ingress:
        url: demo3-cluster24.weavegitops.com/prd/podinfo/
    hpa:
      enabled: true
      maxReplicas: 1
