apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo-dev
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '1.2.5' # {"$promotion": "default:app-podinfo-test-app-host51-cluster24:dev"}
  targetNamespace: app-podinfo-dev
  values:
    service:
      enabled: false
      externalPort: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/service-upstream: "true"
      hosts:
        - host: demo3-cluster24.weavegitops.com
          paths:
            - path: "/dev/podinfo/?(.*)"
              pathType: Prefix
            - path: "/dev/(api/?.*)"
              pathType: Prefix
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for dev"
      color: ""
    canary:
      enabled: true
      loadtester:
        url: flagger-loadtester.flux-system
      ingress:
        url: demo3-cluster24.weavegitops.com/dev/podinfo/
    hpa:
      enabled: true
      maxReplicas: 1
