apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo-prd
  annotations:
    metadata.weave.works/app-url: http://demo3-cluster27.weavegitops.com/prd/podinfo/
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '1.5.38' # {"$promotion": "devteam1:app-podinfo-devteam1-host25-cluster30:prd"}
  targetNamespace: app-podinfo-prd
  test:
    enable: true
    timeout: 5m
    ignoreFailures: false
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  values:
    service:
      enabled: false
      externalPort: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/service-upstream: "true"
      hosts:
        - host: demo3-cluster27.weavegitops.com
          paths:
            - path: "/prd/podinfo/?(.*)"
              pathType: Prefix
            - path: "/prd/(api/?.*)"
              pathType: Prefix
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for prd"
      color: ""
    canary:
      enabled: true
      loadtester:
        url: flagger-flagger-loadtester.flagger
      ingress:
        url: demo3-cluster27.weavegitops.com/prd/podinfo/
    hpa:
      enabled: true
      maxReplicas: 1
