apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  labels:
    templates.weave.works/template-name: app-podinfo-chart-and-pipeline-devteam1
    templates.weave.works/template-namespace: default
  name: app-podinfo-workload-cluster
  namespace: devteam1
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weavegitops/application-promotion-podinfo\",\"head_branch\":\"wge-create-branch-wmpao\",\"base_branch\":\"main\",\"title\":\"Create resource \",\"description\":\"This PR creates a app-podinfo-chart-and-pipeline-devteam1 instance\",\"template_name\":\"app-podinfo-chart-and-pipeline-devteam1\",\"parameter_values\":{\"CLUSTER_NAME\":\"workload-cluster\",\"CLUSTER_NAMESPACE\":\"devteam1\",\"CLUSTER_URL\":\"workload-cluster.devteam1.sa-demo.cx.weave.works\",\"DEV_NAMESPACE\":\"app-podinfo-dev\",\"PRD_NAMESPACE\":\"app-podinfo-prd\",\"STG_NAMESPACE\":\"app-podinfo-stg\"},\"commit_message\":\"Create app-podinfo-chart-and-pipeline-devteam1 instance\",\"credentials\":{},\"template_namespace\":\"devteam1\",\"template_kind\":\"GitOpsTemplate\"}"
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: podinfo
  environments:
  - name: dev
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: workload-cluster
        namespace: devteam1
      namespace: app-podinfo-dev
  - name: stg
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: workload-cluster
        namespace: devteam1
      namespace: app-podinfo-stg
  - name: prd
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: workload-cluster
        namespace: devteam1
      namespace: app-podinfo-prd
  promotion:
    manual: false
    strategy:
      pull-request:
        baseBranch: main
        secretRef:
          name: promotion-credentials-app-podinfo-workload-cluster
        type: github
        url: https://github.com/weavegitops/application-promotion-podinfo
