apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  labels:
    templates.weave.works/template-name: app-podinfo-chart-and-pipeline-devteam1
    templates.weave.works/template-namespace: default
  name: app-podinfo-devteam1-host25-cluster30
  namespace: devteam1
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weavegitops/application-promotion-podinfo.git\",\"head_branch\":\"wge-create-branch-sso3yg\",\"title\":\"Create resource \",\"description\":\"This PR creates a app-podinfo-chart-and-pipeline-devteam1 instance\",\"template_name\":\"app-podinfo-chart-and-pipeline-devteam1\",\"parameter_values\":{\"CLUSTER_NAME\":\"devteam1-host25-cluster30\",\"CLUSTER_NAMESPACE\":\"devteam1\",\"DEV_NAMESPACE\":\"app-podinfo-dev\",\"ENV_GROUP\":\"demo3\",\"PRD_NAMESPACE\":\"app-podinfo-prd\",\"SHARED_PRD_CLUSTER_NAME\":\"team-shared-host51-cluster27\",\"SHARED_PRD_CLUSTER_NAMESPACE\":\"default\",\"STG_NAMESPACE\":\"app-podinfo-stg\"},\"commit_message\":\"Create app-podinfo-chart-and-pipeline-devteam1 instance\",\"credentials\":{},\"template_namespace\":\"devteam1\",\"template_kind\":\"GitOpsTemplate\"}"
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: podinfo
  environments:
  - name: dev
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: devteam1-host25-cluster30
        namespace: devteam1
      namespace: app-podinfo-dev
  - name: stg
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: devteam1-host25-cluster30
        namespace: devteam1
      namespace: app-podinfo-stg
  - name: prd
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: devteam1-host25-cluster30
        namespace: devteam1
      namespace: app-podinfo-prd
    - clusterRef:
        kind: GitopsCluster
        name: team-shared-host51-cluster27
        namespace: default
      namespace: app-podinfo-prd
  promotion:
    manual: false
    strategy:
      pull-request:
        baseBranch: main
        secretRef:
          name: promotion-credentials-app-podinfo-devteam1-host25-cluster30
        type: github
        url: https://github.com/weavegitops/application-promotion-podinfo
