name: Build and Release Container

on:
  pull_request:
    branches:
      - main
      
permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check_versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # important parameter

    - name: Container Version
      id: version
      run: |
        VERSION=$(grep "var VERSION" pkg/version/version.go | sed -e 's/^var VERSION = "//' -e 's/"$//')
        echo "The container version will be set to ${VERSION}"
        echo ::set-output name=VERSION::${VERSION}
        HELM_VERSION=$(cat charts/podinfo/Chart.yaml | yq .version)
        echo "The Helm Chart version: ${HELM_VERSION}"
        echo ::set-output name=HELM_VERSION::${HELM_VERSION}
        HELM_CONTAINER_VERSION=$(cat charts/podinfo/Chart.yaml | yq .appVersion)
        echo "The Helm Chart Container version: ${HELM_CONTAINER_VERSION}"
        if [ "$VERSION" != "$HELM_CONTAINER_VERSION" ]; then
          echo "The Container version and Helm container version should be equal, exiting"
          exit 1
        fi

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
               ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION  }}


